export const jsonObject = {
  'bf558674-ab85-46ba-806f-bb7188eb9c10': {
    'type': 'SearchService',
    'parentType': 'searchService',
    'title': 'Search Service',
    'order': '1',
    'group': '0',
    'mandatory': true,
    'refreshOn': ['bf558674-ab85-46ba-806f-bb7188eb9c10'],
    'render': [],
    'defaultValue': '',
  },
  'bdc7c919-4aef-40d4-bb44-19174c6b0af2': {
    'type': 'InputBox',
    'parentType': 'inputBox',
    'title': 'Enter some text',
    'order': '1',
    'group': '0',
    'mandatory': true,
    'refreshOn': ['bdc7c919-4aef-40d4-bb44-19174c6b0af2'],
    'render': {
      'placeHolder': '',
      'multipleLine': false,
    },
    'defaultValue': '',
  },
  '3751e4bf-a6a1-4768-bc3d-3b2cb83d0cd3': {
    'type': 'Textarea',
    'parentType': 'inputBox',
    'title': 'Some more text',
    'order': '2',
    'group': '0',
    'mandatory': true,
    'refreshOn': [],
    'render': {
      'placeHolder': '',
      'multipleLine': true,
    },
    'defaultValue': '',
  },
  '02e0732f-79ff-4b27-9dca-4804266e1800': {
    'type': 'ServiceSuspend',
    'parentType': 'dropdown',
    'title': 'Suspend Service',
    'order': '4',
    'group': '0',
    'mandatory': true,
    'refreshOn': [],
    'render': {
      'items': {
        '0': 'No',
        '1': 'Yes',
      },
      'groups': false,
      'allowMultiple': false,
    },
    'defaultValue': '',
  },
  'eeb415a6-c36f-4ac5-acd2-f47f6c38bea4': {
    'type': 'ServiceInfo',
    'parentType': 'serviceInfo',
    'title': 'Service Info',
    'order': '5',
    'group': '0',
    'mandatory': false,
    'refreshOn': ['bf558674-ab85-46ba-806f-bb7188eb9c10'],
    'render': {
      'showEmployeeInfo': true,
    },
    'defaultValue': '',
  },
  '5b8a8164-3041-4c18-a168-d262adf86d14': {
    'type': 'Text',
    'parentType': 'text',
    'title': 'Text',
    'order': '6',
    'group': '0',
    'mandatory': false,
    'refreshOn': [],
    'render': {
      'text': 'this is text',
      'textHexColour': '#000000',
      'textFontSize': 12,
      'backgroundHex': '#bfefff',
      'titleHexColour': '#2e78bc',
      'titleFontSize': 20,
    },
    'defaultValue': '',
  },

  // Original Value from Database
  // '16b3829b-404f-4743-9142-fd1ea48a0ba3': {
  //   id: '16b3829b-404f-4743-9142-fd1ea48a0ba3',
  //   type: 'InputBox',
  //   parentType: 'InputBox',
  //   title: 'Input Box:',
  //   order: '1',
  //   group: '0',
  //   properties: {
  //     placerHolder: {
  //       value: 'placeholder value',
  //       display: 'placeholder display',
  //     },
  //     MANDATORY_STATUS: {
  //       value: '1',
  //       display: 'Yes',
  //     },
  //     'marginTop': {
  //       'value': '10',
  //       'display': '50',
  //     },
  //     'marginBelow': {
  //       'value': '10',
  //       'display': '50',
  //     },
  //   },
  //   value: '',
  //   tag: '',
  // },
  // '7a464af3-806c-45a3-9b14-a6da63618159': {
  //   'id': '7a464af3-806c-45a3-9b14-a6da63618159',
  //   'type': 'Text',
  //   'parentType': 'Text',
  //   'title': 'Use this form to terminate a mobile service that you no longer want',
  //   'order': '2',
  //   'properties': {},
  //   'group': 0,
  //   value: '',
  //   'tag': '',
  // },
  // '8be3deec-a3f3-408b-ad87-5ee31b25c782': {
  //   'id': '8be3deec-a3f3-408b-ad87-5ee31b25c782',
  //   'type': 'Textarea',
  //   'parentType': 'Textarea',
  //   'title': 'Please provide as much detail as possible, such as any error messages received or the update you require?',
  //   'order': '3',
  //   'properties': {
  //     'placerHolder': {
  //       'value': '',
  //       'display': '',
  //     },
  //     'MANDATORY_STATUS': {
  //       'value': '1',
  //       'display': 'Yes',
  //     },
  //   },
  //   value: '',
  //   'group': 0,
  //   'tag': '',
  // },
};
