export const Strings = Object.freeze({
  search: 'Search...',
  noCatalog: 'Look like there are no any data found at the moment.',
  dropDownPlaceholder: 'Select item',
  outOfStock: 'Out of Stock',
  brand: 'Brand',
  color: 'Colour',
  size: 'Size',
  errorMessage: 'Please enter value',
  dropDownErrorMessage: 'Please select value',
  catalogErrorMessage: 'Please select any one',
  submit: 'Submit',
  previous: 'Previous',
  next: 'Next',
  cancel: 'Cancel',
  selectDevice: 'Select Device',
  selectedDevice: 'Selected Device',
  selectPlaceholder: 'Please Select',
  select: 'Select',
  allDevices: 'All Devices',
  selectedDevices: 'Selected Devices',
  selectState: 'Select State',
  streetLine1: 'Street Line 1',
  streetLine2: 'Street Line 2',
  city: 'City',
  zip: 'ZIP',
  state: 'State',
  type: 'Selection',
  emailValidation: 'Email address is not proper formate',
  deviceManufacturer: 'Device Manufacturer',
  device: 'Device',
  serviceStatus: 'Service Status',
  vendor: 'Vendor',
  tariffAndPlan: 'Tariff / Plan',
  costCenter: 'Cost Center',
  serialNumberAndIMEINumber: 'Serial Number/ IMEI Number',
  contractEndDate: 'Contract End Date',
  eligibleUpgrade: 'Eligible date for upgrade',
  createNewSite: 'Create A New Site',
  siteName: 'Site Name',
  buildingName: 'Building Name',
  postCodeAndZipCode: 'Post Code / Zip Code',
  stateAndCountry: 'State / Country',
  country: 'Country',
  latitude: 'Latitude',
  longitude: 'Longitude',
  contactPhoneNumber: 'Contact Phone Number',
  contactEmail: 'Contact Email',
  contactName: 'Contact Name',
  siteCode: 'Site Code',
  required: 'Required',
  firstName: 'First Name',
  lastName: 'Last Name',
  email: 'Email',
  dateCentre: 'Date Centre',
  employeeID: 'Employee ID / Payroll',
  createNewEmployee: 'Create A New Employee',
  selectDataCenter: 'Select Data Centre',
  useAddress:'US Address'
});
